name: Manual Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.4)'
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "v${{ inputs.version }}"
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Configure npm for GitHub Packages
        run: |
          echo "@kinetic-apps:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          
      - name: Install dependencies
        run: npm install
        
      - name: Build package
        run: npm run build
        timeout-minutes: 15
        
      - name: Verify version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ "$PACKAGE_VERSION" != "${{ inputs.version }}" ]; then
            echo "Package version ($PACKAGE_VERSION) doesn't match input version (${{ inputs.version }})"
            exit 1
          fi
          
      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish